### PR TITLE
BUG: hamburger icon needs to replace with close icon if menu opens #362

### PR DESCRIPTION
**Pull request by kapilG0**
## Related Issue
None 

## Description
BUG: hamburger icon needs to replace with close icon if menu opens #362

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/subhadeeproy3902/BloxAI/assets/59639410/554b652a-e65d-45ad-8cec-96e9174c9212

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
@kapilG0 Make the changes according to the latest PR.
The version has changed basically !
I am closing this, You `git pull` and do the necessary changes and send me the PR again. I will check it up then n there .
image

**Comment by kapilG0** [comment]
> @kapilG0 Make the changes according to the latest PR. The version has changed basically ! I am closing this, You `git pull` and do the necessary changes and send me the PR again. I will check it up then n there . image

Actually I took pull then did changes . Let me check

**Comment by subhadeeproy3902** [comment]
@kapilG0 Just the latest merge i did resolved this problem but your PR was raised previously thats why ig u faced error. DO a new PR i am sure it will work !

**Comment by kapilG0** [comment]
> @kapilG0 Just the latest merge i did resolved this problem but your PR was raised previously thats why ig u faced error. DO a new PR i am sure it will work !

Ok i will check. And update

**Pull request closed without merging**
