### PR TITLE
Footer section anchor tag hovering effect with color change.

### PR DESCRIPTION
**Pull request by sakeel-103**
#315 solved.

#315 
Footer section hovering effect.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
video -

https://github.com/subhadeeproy3902/BloxAI/assets/136844498/5f372ed9-f2e9-4c62-a6db-000372b188c6

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by sakeel-103** [comment]
@subhadeeproy3902 
as per your suggestion I changed only that one effect.

**Comment by subhadeeproy3902** [comment]
@sakeel-103 Why dont u read `Contributing.md` its clearly mentioned to `git pull`

image


All these changes have been done ... i wont accept it ... cuz or else our convex database might become faulty

**Comment by sakeel-103** [comment]
@subhadeeproy3902 
I don't understand, will you please explain "cuz or else our convex database might become faulty" this line.
and please suggest what I should do cuz I'm very new to Next.js tech.

**Comment by subhadeeproy3902** [comment]
@subhadeeproy3902 do git pull... u have made changes in convex folder as well check the files u have changed in this PR. generate a new PR if u want to ithout changing other than the issue resolving !

**Pull request closed without merging**
