### PR TITLE
Create greetings.yaml

### PR DESCRIPTION
**Pull request by sanmarg**
Added Workflow for #38

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
U are requested to read the README.md @sanmarg

**Comment by subhadeeproy3902** [comment]
@sanmarg please check the contributors section in the README.md. Then raise the PR again

**Comment by sanmarg** [comment]
Could you please add the labels to it considering its technicalities.

**Comment by subhadeeproy3902** [comment]
> Could you please add the labels to it considering its technicalities.

The issue has already been labeled and is closed ! check issue #38

**Pull request merged**
