### PR TITLE
Added Review Us Page. [Issue #18] 

### PR DESCRIPTION
**Pull request by Manav173**
Added customer review page against issue no. #18 made the changes as requested by you in PR https://github.com/subhadeeproy3902/BloxAI/pull/57

Kindly check and merge this PR.

P.S would really appreciate if you can raise the issue level from 1 to 2/3.

### CODE REVIEW

**Comment by AMANKANOJIYA** [comment]
### Updates

- [ ] Update the Carousal Speed (not readable at this speed)
- [ ] Styling issues with the Review Form 

image
_Still have the scroll height
The form does not fit the screen_

**Suggestions:**

- It would be better if we could improve the design of the review page. In addition, we can also make customer testimonials in other designs
- where the review form is not highlighted according to the UX. If we can make the form more appealing

**Comment by Manav173** [comment]
@subhadeeproy3902 Can you please raise the issue level from 2 to 3 as I have added testimonials also in the contact page and you have assigned level 3 for that same issue in PR #114.

**Comment by subhadeeproy3902** [comment]
but #114 one UI is too good compared to this one !

**Comment by Manav173** [comment]
but that one is based totally on my structure and in the PR 80 you have assigned level 3 for a form. Referring to that i have also testimonials in the review page with the  auto slider effect. @subhadeeproy3902

**Pull request merged**
