### PR TITLE
Updated contributing.md file by adding git commands 

### LINKED ISSUE #140: DOC: Update contributing.md file by adding git commands
### What's wrong with the existing documentation

The existing documentation does not contain git commands. It just mentions about the steps to follow while contributing.

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Amruta7203**
Resolves #140 

## Description
Added the necessary git commands 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [x ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
@Amruta7203 add up yourself in the Contributor.ts

**Comment by subhadeeproy3902** [comment]
@Amruta7203 Why u closed this ??... i was about to merge it

**Comment by subhadeeproy3902** [comment]
@Amruta7203 is there any problem ?

**Comment by Amruta7203** [comment]
@subhadeeproy3902 Maybe that happened because I synced the fork. I did not do that intentionally.

**Comment by Amruta7203** [comment]
Request you to add the gssoc labels to this.

**Comment by subhadeeproy3902** [comment]
@Amruta7203 where is your contribution ?? ...
I said u changed the Contributing.md file giving the`git` commands... along with it write ur details in Contributors.ts file. Please check previous convo

**Comment by subhadeeproy3902** [comment]
Yes, I know .. its okay ... in that PR i asked only to add ur details as contributor nothing else. But now check it ->

image

@Amruta7203 u have only added your details. You didnt solve the issue 

> @subhadeeproy3902 Maybe that happened because I synced the fork. I did not do that intentionally.

**Pull request closed without merging**
