### PR TITLE
Added "About Us" Page with Information about Blox AI

### LINKED ISSUE #107: BUG: The AboutUs link in footer not redirecting
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @subhadeeproy3902 ,

## The Issue is -

 The "About Us" link in the footer of the website. The link does not redirect properly when clicked, which can lead to a poor user experience.

Could you please assign this task to me? I am confident that I can resolve the issue promptly.

## Screenshot - 

I am attaching the screenshot for more understanding -

https://github.com/subhadeeproy3902/BloxAI/assets/145179532/02c0c8e4-be02-4641-a181-a0647f98144f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Aniket-2504**
# Added abouts us page with proper adjustment

Thank you so much @subhadeeproy3902 , for giving me this opportunity.

## Related Issue
Fixes #107 

## Description
I have created an "About Us" page for the website. This page includes detailed information about Blox AI, such as its features, tech stack, and the creators of the AI. I am also considering changing the "About" link to "Home" for better navigation since the "About Us" page is now available.

### Added "About Us" Page:

1. Included information about Blox AI.
2. Listed the features of Blox AI.
3. Detailed the tech stack used in Blox AI.
4. Added a section for the creators of Blox AI.

## Navigation Changes:

Proposed changing the "About" link to "Home" for better user experience.If you want then 

## Type of PR

- [ ] Feature enhancement

## Screenshots- 

Screenshot 2024-05-24 085043
Screenshot 2024-05-24 085035
Screenshot 2024-05-24 085019
Screenshot 2024-05-24 084955
Screenshot 2024-05-24 084944
Screenshot 2024-05-24 084925

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.

## Additional context:
 Feel free to tell me about the changes.and if you add something in that

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
@Aniket-2504 Please dont delete the .env.example file.
Push it back !!.
And please do read Contributing.md file nicely

**Comment by Aniket-2504** [comment]
I dont delete the file just change to env.local

**Comment by Aniket-2504** [comment]
can I rename the env file and just push it ?

**Comment by subhadeeproy3902** [comment]
@Aniket-2504 yes good. Now list up your contribution. Read Contributing.md

**Comment by Aniket-2504** [comment]
still sometghing wrong what i do now ?

**Comment by subhadeeproy3902** [comment]
> still sometghing wrong what i do now ?

Read Contributing.md

**Comment by Aniket-2504** [comment]
I added my name in list but what i do with the env file , can you plsese give me some guide?

**Comment by subhadeeproy3902** [comment]
All good now !

**Comment by Aniket-2504** [comment]
But how we gonna merge this PR

**Comment by subhadeeproy3902** [comment]
> But how we gonna merge this PR

U cant, I will after some reviewing .... I will be commenting here and do join the whatsapp group

**Comment by Aniket-2504** [comment]
ok @subhadeeproy3902 , thank you bro appriciate it

**Comment by subhadeeproy3902** [comment]
@Aniket-2504 Its too much poor UI. Check more about `About Us` Pages in tailwind and you can take inspirations from them. But this page is too plan and simple. And do not keep the Owners because its already listed in the `Contributors` page

**Review by subhadeeproy3902 — CHANGES_REQUESTED** [review]
@Aniket-2504 Do change this ... Try to see the UI of home page and this `About Us` page. It too minimal compared to the UI of the website

**Pull request closed without merging**
