### PR TITLE
Feature responsive

### PR DESCRIPTION
**Pull request by sarthakmishra459**
Made Sidebar Responsive and fixed components being cut issue. Also fixed the package.json which was causing build to be failed in vercel. #16 
Sidebar Responsive 1
Sidebar Responsive 2
Component Cut Fix

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
@sarthakmishra459 Please read the README.md and do the necessary things in the PR

**Comment by sarthakmishra459** [comment]
I don't understand I have already updated contributors data. What more necessary changes do I have to do?

**Comment by subhadeeproy3902** [comment]
> I don't understand I have already updated contributors data. What more necessary changes do I have to do?

Woops ! My bad LOL. Well done okay !!

**Comment by Xeven777** [comment]
@sarthakmishra459 . Go throught the readme once, and add yourself as project contributor🥳✨

**Pull request merged**
