### PR TITLE
added workflow as mentioned in issue #120

### LINKED ISSUE #120: Feat: Workflow for closing issues on merging PR linked to that issue
### Describe the feature

As the repo maintainers have to manually close an issue after merging a PR linked with that issue, I propose a workflow where the issue linked with a PR which be automatically closed when that PR is merged by the maintainer and efforts will be saved.

### Add ScreenShots

Close on mege

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
## Related Issue

Fixes #120 

## Description
As the repo maintainers have to manually close an issue after merging a PR linked with that issue, I propose a workflow where the issue linked with a PR which be automatically closed when that PR is merged by the maintainer and efforts will be saved.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Asymtode712** [comment]
@subhadeeproy3902 please add gssoc and level labels as it is made mandatory


labels

**Comment by subhadeeproy3902** [comment]
ohh sorry I forgot !
and do one thing please check contributors.md file

**Comment by subhadeeproy3902** [comment]
@Asymtode712 i checked and i have already given the tags too !

**Comment by Asymtode712** [comment]
@subhadeeproy3902 you have to also give them to the PRs

**Comment by Asymtode712** [comment]
@subhadeeproy3902 please see the SS once again

**Pull request merged**
