### PR TITLE
FileConversion.js added and Server.js is added

### PR DESCRIPTION
**Pull request by Cralsic123**
I have also modified the main server.js file and there I have created an endpoint route to use the FileConversion.js

**New Files Added**

FileConversion.js: This JavaScript file contains server-side logic for handling file downloads and conversions in various formats, including PDF, PPT.

**Integration with Main Server:**

The functionality provided by downloadHandler.js has been integrated into the existing server.js file. The following routes have been defined to handle file downloads in different formats:

/download/pdf: Downloads the editor.tsx file as a PDF.
/download/ppt: Downloads the editor.tsx file as a PowerPoint presentation.

While the basic functionality for file downloads and conversions has been implemented, there are some additional tasks and areas for improvement that need to be addressed:

**Error Handling:** includes handling cases such as file not found, invalid input, or server-side errors.
**Security:** Security measures to protect against potential security vulnerabilities, and prevention of unauthorized access to sensitive files or endpoints.

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
@Cralsic123 This will take time for reviewing. Giving u a response back in 1 day. Look into other issues and thanks a lot for this PR

**Comment by Cralsic123** [comment]
@subhadeeproy3902 Thanks a lot. Hope it works.

**Comment by subhadeeproy3902** [comment]
@Cralsic123 i would ask you to send me a video link where u record the thing up and execute it ! if possible. tomorrow i will be updating the .env.example file for resolving the problem with the env variables

**Comment by subhadeeproy3902** [comment]
@Cralsic123 .env.example file has been added check for the code again and send me a detailed video or screenshots showing the result. Thank you for your collaboration

**Comment by Cralsic123** [comment]
@subhadeeproy3902  on it.

**Comment by Cralsic123** [comment]
Ill provide screenshots.

**Pull request closed without merging**
