### PR TITLE
feat: modal team members

### LINKED ISSUE #344: Feat: Team member's modal
### Describe the feature

Modal having member info and member management for Owner

### Add ScreenShots

Not required!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Sid-80**
## Related Issue
resolves #344 

## Description
Model for team members

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ayush1212612** [comment]
@sanjay-kv  Sir from here this user is getting level 3 for almost all pr's and even just for an one line issue doesn't explaining properly .
Sometimes project owner hide the files changes done by this user i am thinking that it's not a fair contribution for all other contributors .
Please review all pr's of this user and give level accordingly

**Comment by subhadeeproy3902** [comment]
> @sanjay-kv  Sir from here this user is getting level 3 for almost all pr's and even just for an one line issue doesn't explaining properly .
> Sometimes project owner hide the files changes done by this user i am thinking that it's not a fair contribution for all other contributors .
> Please review all pr's of this user and give level accordingly
> 

Hello @Ashmitkumar1 . First of all dont raise any questions cuz u dont check the files and the mentioned things about a whatsapp group. @Sid-80 has been readily working for Blox AI. He has added AI features, teaming, settings, read  write access, file publicity and what not. Please do check the PRs and no files are hidden. I think u dont know that files in a PR can be seen u just havent checked them. Agree to it. 
Next yeah about the one liner. You should be joining the whatsApp group whose link i have posted in in this repo. There are updates everytime and he is gradually giving updates there all the time. So issue raising doesnt matter to me, the PR and files matter. 
Another thing check the issues how many level1 I have assigned but no one is working on them. So better before raising a query justify yourself. 
Thank You. Others like @chitraa-jain also has given one liner issues. As said issues doesnt matter to me, enhancing this project does.

**Comment by Sid-80** [comment]
@Ashmitkumar1 I don't know what personal grudge you are having.
If you can develop following things in a month, I will be giving all points to you!!
1. AI-Integrated Documentation
2. AI-Integrated Flowchart generation
3. Team collaboration with code
4. Team collaboration with link
5. Team collaboration backend + UI
6. User Settings : backend + ui
7. Team settings : backend + ui
8. Profile section : backend+ ui
9. Public and private file : backend + ui
10. Read and write file : backend + ui

**Comment by Ashmitkumar1** [comment]
@subhadeeproy3902  ok so why are you hiding files for sometime like i saw yesterday you hides the file changes

**Comment by Ashmitkumar1** [comment]
> @Ashmitkumar1 I don't know what personal grudge you are having. If you can develop following things in a month, I will be giving all points to you!!
> 
> 1. AI-Integrated Documentation
> 2. AI-Integrated Flowchart generation
> 3. Team collaboration with code
> 4. Team collaboration with link
> 5. Team collaboration backend + UI
> 6. User Settings : backend + ui
> 7. Team settings : backend + ui
> 8. Profile section : backend+ ui
> 9. Public and private file : backend + ui
> 10. Read and write file : backend + ui

If yes ok i will do and i also want to point out is that bro you took level 3 for read and write seperately and same for public and private

**Comment by Sid-80** [comment]
If you are having little bit knowledge of Software engineering lifecycle then you can understand every feature can't build overnight. You have to go step by step. For building read, write, public, private you have to go from scratch by making implementation of backend schema for each feature then make api for it test the api, create ui then integrate the api. There is not only one section where read, write, public, private will be integrated like dashboard, workspace, settings page, team settings page...

**Comment by Sid-80** [comment]
Bro Lines of code are not important. The feature you built is working or not that is important.
https://github.com/girlscript/gssoc-website-new/pull/286
Even in above PR I made the changes of 26 lines then also sanjay sir assigned it level 3
Because their designs came into existence

**Comment by sanjay-kv** [comment]
image


@Sid-80 This is a big issue Sid, im still trying to understand what happening. so don't consider this has any blame or allegation. 
I'm explaining to you whats odd in your contributions:

1. The frequency of PR you doing is strange. if its level1 issue I wouldn't mind, but it categorise has level3 issue which means complicated issues. 
image

2. None of these issue are reviewed and directly merged by admin @subhadeeproy3902 
image

3. @subhadeeproy3902 I read your comment regarding the issue raising, we are in a program with another 200+projects and everyone following guidelines, like raising issue and creating respective PR is the right option. I do agree internal communication can be good. 
But its strange one line explanation of issues & PR in minutes to level3 .

4. @Sid-80 I got your reply to @Ashmitkumar1 on the internal PR for girlscript. 
I do agree the lines of code is less and implementation was huge change to existing enhancement by fetching API. 
but do check the issue link of the same https://github.com/girlscript/gssoc-website-new/issues/264

We have a long thread to do such small implementation. This thing is missing on your contributions. 
and as a reviewers its often get hard time to understand what exactly you did. 

- Looking at the code base never gives a good idea to overall view unless you document or well address the issue. 
- internal communication can be done at the your comfort. but in terms of program if you followed a kinda communication https://github.com/girlscript/gssoc-website-new/issues/264 like these on your respective PR these issue can be easily avoided. 
right @Ashmitkumar1 

Its not just @Ashmitkumar1 raised this issue, my inbox is filled with yours and Anish(other contributor) contributions PR links. 

I also suggest admin to follow thread communication just like this, it would be really helpful if you have to look back to the developments by hiding confidential data and file, and whatsapp communication is not viable in long term.

**Comment by sanjay-kv** [comment]
image

@subhadeeproy3902 I was referring to this anish

**Comment by subhadeeproy3902** [comment]
@sanjay-kv oh actually not this one but there is another Anish who is the admin as well of this project 😅

**Pull request merged**
