### PR TITLE
Added CONTRIBUTING.md

### LINKED ISSUE #30: Missing CONTRIBUTING.md File in Repository
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
Fixes #30

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
Go through the Contributors Section in the README.md @suhanipaliwal

**Comment by suhanipaliwal** [comment]
> Go through the Contributors Section in the README.md @suhanipaliwal

Yes I have seen that part and I have also included that part in the CONTRIBUTING.md file made by me.

**Comment by subhadeeproy3902** [comment]
> > Go through the Contributors Section in the README.md @suhanipaliwal
> 
> Yes I have seen that part and I have also included that part in the CONTRIBUTING.md file made by me.

Thanks a lot ... but I wanted u to add ur details in the Contributors.ts file as well.. Dont u wanna do it XD

**Comment by suhanipaliwal** [comment]
Please add the labels of gssoc and level1 on this pull request as well according to gssoc guidelines.

**Pull request merged**
