### PR TITLE
Ensured visibility of the scroll up button

### PR DESCRIPTION
**Pull request by chitraa-cj**
## Related Issue
#420 

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@chitraa-cj Can I ask you why did you Pull Request for the issue that was assigned to me, even tho you have your own assigned issues? This is against the guidelines and code of conduct you know it right?

**Comment by subhadeeproy3902** [comment]
image

@

**Comment by subhadeeproy3902** [comment]
image

@chitraa-cj

**Comment by MastanSayyad** [comment]
@subhadeeproy3902 the issue is assigned to me then why are you assigning the PR to this contributor?

**Comment by subhadeeproy3902** [comment]
@MastanSayyad She raised a PR first. cant help !
If you can raise your PR without any errors like in her then I will be checking it up too and merging it closing this. 
Simple as that. A person can get assigned to other's issues as well. If you fail to show up for your issue thats not my problem

**Comment by MastanSayyad** [comment]
According to the GSSOC guidelines the PR can be only generate by the one who is assigned to that issue! 

Without raising and assigned issue GSSOC contributors are not allowed to make PR

If the issue assigned to me then I'm the only one who can solve it and make the PR if i'm unable to do so then only you can assign the issue to another contributor (the limit is 5 days if the assign contributor fails to solve the issue) and accept their PR @subhadeeproy3902 

As I'm a GSSOC and girscript contributor and under the guidance of sanjay (gssoc mainatiner) I have analyzed and reviewed this profile ans need to report this activity as this particular contributor is violating the gssoc guidelines and scoring on the leaderboard! 

Please let me know if you still have any doubt, if so i can provide you the contributing guidelines of GSSOC 24!

**Comment by MastanSayyad** [comment]
You have to look as perspective of **GSSOC Project Admin,** your saying is right but it does not apply to gssoc open source program.

**Pull request closed without merging**
