### PR TITLE
Added a Dedicated Contributing Guidelines Page to The Website 

### LINKED ISSUE #458: Feat: Add a Dedicated Contributing Guidelines Page to The Website
### Describe the feature

Hey @subhadeeproy3902 

I would like to add a dedicated page contributing guidelines the website to ensure the contributors have clarity about it.

image

### Add ScreenShots

Like this

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
## Related Issue
- issue closes #458 

## Description
Hey @subhadeeproy3902 

I have added a Dedicated Contributing Guidelines Page to The Website 

image

image

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by RadhikaMalpani1702** [comment]
@subhadeeproy3902  Please take a look and review this PR
Also could you please increase the level it was my first time creating a page in next.js using typescript so it took me more time however if not then it's also fine, Thank You!

**Comment by subhadeeproy3902** [comment]
image
@RadhikaMalpani1702 Make sure to fix this !

**Comment by RadhikaMalpani1702** [comment]
@subhadeeproy3902  I have fixed it please check it

**Comment by subhadeeproy3902** [comment]
image

@RadhikaMalpani1702 Still not fixed !!

**Comment by RadhikaMalpani1702** [comment]
@subhadeeproy3902 I have fixed this issue please review and merge it

**Comment by RadhikaMalpani1702** [comment]
@subhadeeproy3902 Please merge this PR

**Comment by subhadeeproy3902** [comment]
@RadhikaMalpani1702 
image


It has a lot of errors. Check first nicely then send a PR !

**Pull request closed without merging**
