### PR TITLE
Enhanced Feedback form 

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
## Description
I have enhanced the feedback form by updated the whole design and the design i used  is following the theme of the contact page .

Closes : #231

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/subhadeeproy3902/BloxAI/assets/118350936/33f0eece-7893-4c1a-afaa-837df591f00a

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@subhadeeproy3902  If you didn't like anything please let me know i will do that and i have to write many css that matches the theme and also make it responsive so please give the level accordingly .

**Comment by subhadeeproy3902** [comment]
it look too much copied from the Contact page... please change it and search for Feedback forms on Google @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
I did that because the theme remains same but i will  change it please wait

**Comment by Ayushmaanagarwal1211** [comment]
@subhadeeproy3902 Updates please review it

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/subhadeeproy3902/BloxAI/assets/118350936/9fc5d242-f027-4770-9f29-8f6e24b866d3

**Review by subhadeeproy3902 — CHANGES_REQUESTED** [review]
@Ayushmaanagarwal1211 
1. Whole black colour isnt suitable for UI
2. SVG shouldnt be blue cuz it then hampers the orangish theme
3. I will suggest u to check aceternity or magicui elements and check internet for building a nice UI.
4. I wont suggest the to give a white box shadow !!
5. Make changes accordingly such that the UI is adjustable as per the theme (dark and light)

**Pull request closed without merging**
