### PR TITLE
added sorting options on list header

### LINKED ISSUE #76: Feat: Sorting options
### Describe the feature

Now it is sorted by created at. We can add a sort option in the header list, such as sorting the list by name or editing. This feature enhances user experience.

### Add ScreenShots

sort

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ronisarkarexe**
## Related Issue
fixed #76 

## Description
added sorting options on list header

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Before Sort
prev_sort

After Sort
after-sort

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
@ronisarkarexe 
image


Also git pull... cuz i merged ur previous PR

**Comment by ronisarkarexe** [comment]
> @ronisarkarexe image
> 
> Also git pull... cuz i merged ur previous PR

ok

**Comment by Xeven777** [comment]
After successful merge, dont forget to add ur name in the contributors list 💡😇

**Comment by subhadeeproy3902** [comment]
@ronisarkarexe hasnt is fixed it yet ?

**Comment by ronisarkarexe** [comment]
> @ronisarkarexe hasnt is fixed it yet ?

fixed

**Comment by ronisarkarexe** [comment]
> After successful merge, dont forget to add ur name in the contributors list 💡😇

I already added my previous issue 😇.

**Pull request merged**
