### PR TITLE
added workflow as mentioned in issue #116

### LINKED ISSUE #116: Feat: Auto Commenting feature for PR Merged
### Describe the feature

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks

### Add ScreenShots

PR merged

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
## Related Issue
 
Fixes #116 

## Description
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
@Asymtode712 read contributors.md please

**Comment by Asymtode712** [comment]
@subhadeeproy3902 have commented the code and hence carried out all the tasks, please review and merge this PR

**Comment by Asymtode712** [comment]
@subhadeeproy3902 Also add the labels to this PR
Thank You!

**Comment by subhadeeproy3902** [comment]
@Asymtode712 PRs are not labeled only issues are .... but please do check the contributors.md. Its clearly written ... go through the README first !

**Comment by Asymtode712** [comment]
labels

@subhadeeproy3902 the program manager has clearly stated that PR as well as Issues both must be label, open discord and check it once

**Comment by subhadeeproy3902** [comment]
@Asymtode712 I have already talked to project managers of mine !
So please, dont question about this !
the issue was labeled from the first and u please do check CONTRIBUTING.md file

**Pull request merged**
